# -*- coding: utf-8 -*-
"""finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEmcd4LroNpsTV3U3EZhwrSXa9r5Xi_B
"""

#! pip install gliner
#! pip install accelerate -U

# download data
#! wget https://huggingface.co/datasets/urchade/synthetic-pii-ner-mistral-v1/resolve/main/data.json

import json
import random

train_path = "rna_structures_parsed_ts0.json"  #data.json"

with open(train_path, "r") as f:
    data = json.load(f)

print('Dataset size:', len(data))

random.shuffle(data)
print('Dataset is shuffled...')

train_dataset = data[:int(len(data)*0.9)]
test_dataset = data[int(len(data)*0.9):]

print('Dataset is splitted...')

import os
os.environ["TOKENIZERS_PARALLELISM"] = "true"

import torch
from gliner import GLiNERConfig, GLiNER

from transformers import AutoTokenizer,AutoModel

from gliner.training import Trainer, TrainingArguments
from gliner.data_processing.collator import DataCollatorWithPadding, DataCollator
from gliner.utils import load_config_as_namespace
from gliner.data_processing import WordsSplitter, GLiNERDataset

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')
print(device)
tokenizer = AutoTokenizer.from_pretrained("GLiNER/logs/final_model", use_fast=False, local_files_only=True)
model_name = "GLiNER/logs/final_model"
model1 =  AutoModel.from_pretrained(model_name)
model_vocab_size = model1.get_input_embeddings().num_embeddings
print(f"Model embedding vocab size: {model_vocab_size}")


model = GLiNER.from_pretrained("GLiNER/logs/final_model", local_files_only=True) #urchade/gliner_small")
print(f"Tokenizer vocab size: {len(tokenizer)}")
print(f"Model vocab size: {model.config.vocab_size}")
#model.resize_token_embeddings(len(tokenizer))

# Print all tokens in the tokenizer
#for token, idx in tokenizer.get_vocab().items():
#    print(f"{idx}: {token}")
# Print the size of embedding layer
# For GLiNER, access the transformer inside the model
# Print all top-level attributes and submodules
'''
print("Top-level attributes:")
print(dir(model))

print("\nSubmodules:")
for name, module in model.model.named_modules():
    print(name)

for k, v in model.__dict__.items():
    print(k, type(v))
'''
embedding_layer = model.model.token_rep_layer.bert_layer.model.embeddings.word_embeddings
#print("Embedding matrix shape:", embedding_layer.weight.shape)

# Print first 20 tokens and their IDs
vocab_size = embedding_layer.weight.shape[0]
for idx in range(min(vocab_size, 20)):
    token = tokenizer.convert_ids_to_tokens(idx)
    print(f"{idx}: {token}")

#transformer = model.model.token_rep_layer.bert_layer.model

#transformer.resize_token_embeddings(len(tokenizer))

#model.resize_token_embeddings(len(tokenizer))

# use it for better performance, it mimics original implementation but it's less memory efficient
data_collator = DataCollator(model.config, data_processor=model.data_processor, prepare_labels=True)

# Optional: compile model for faster training
model.to(device)
#print("done")

# calculate number of epochs
num_steps = 500
batch_size = 16
data_size = len(train_dataset)
num_batches = data_size // batch_size
num_epochs = max(1, num_steps // num_batches)

training_args = TrainingArguments(
    output_dir="models",
    learning_rate=5e-6,
    weight_decay=0.01,
    others_lr=1e-5,
    others_weight_decay=0.01,
    lr_scheduler_type="linear", #cosine
    warmup_ratio=0.1,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=num_epochs,
#    evaluation_strategy="steps",
    save_steps = 100,
    save_total_limit=10,
    dataloader_num_workers = 0,
    use_cpu = False,
    report_to="none",
    )

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=model.data_processor.transformer_tokenizer,
    data_collator=data_collator,
)

trainer.train()

#trained_model = GLiNER.from_pretrained("models/checkpoint-100", load_tokenizer=True)

trained_model = GLiNER.from_pretrained("models/checkpoint-100", load_tokenizer=True)

text = """
Cristiano Ronaldo dos Santos Aveiro (Portuguese pronunciation: [kɾi▒~C▒~Htj▒~Pnu ▒~A▒~T▒~Hnaldu]; born 5 February 11
985) is a Portuguese professional footballer who plays as a forward for and captains both Saudi Pro League club Al Nassr and the Portugal national team. Widely regarded as one of the greatest players of all time, Ronaldo has won five Ballon d'Or awards,[note 3] a record three UEFA Men's Player of the Year Awards, and four European Golden Shoes, the most by a European player. He has won 33 trophies in his career, including seven league titles, five UEFA Champions Leagues, the UEFA European Championship and the UEFA Nations League. Ronaldo holds the records for most appearances (183), goals (140) and assists (42) in the Champions League, goals in the European Championship (14), international goals (128) and international appearances (205). He is one of the few players to have made over 1,200 professional career appearances, the most by an outfield player, and has scored over 850 official senior career goals for club and country, making him the top goalscorer of all time.
"""

text = "ACGCUUUACGUUUU"
# Labels for entity prediction
labels = ["multiloop", "hairpin"] # for v2.1 use capital case for better performance

# Perform entity prediction
entities = trained_model.predict_entities(text, labels, threshold=0.0)

# Display predicted entities and their labels
for entity in entities:
    print(entity["text"], "=>", entity["label"])

import torch

torch.__version__

import transformers

transformers.__version__

import huggingface_hub

huggingface_hub.__version__

import accelerate

accelerate.__version__


